server:
  port: 5555
spring:
  application:
    name: config-client-dev-v01
  cloud:
    config:
      label: master
      name: config
      profile: dev
      uri: http://config-3344.com:3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
